### ISSUE TITLE
SSL cert error

### ISSUE THREAD

**Issue by tullo** [boyers/doesgoogleexecutejavascript#1]
Hi, there seems to be an https issue as the browsers I've tested with (Chrome, FF) all come up with a SSL CERT ERROR or BAD RESPONSE for the provided link https://doesgoogleexecutejavascript.com/

**Comment by stepchowfun** [comment]
I noticed this too. The HTTP version seems to work fine, but I'm not sure what's up with the SSL cert. I'll ask Cloudflare about it.

**Comment by stepchowfun** [comment]
Actually, now I remember the problem. I asked them about this a while ago, and they said:

> Your domain name contains a trademark - 'google'. We will not be able to issue an SSL for this.

(Their free plan doesn't allow me to upload a custom certificate.)
